# Generated by Django 5.2.8 on 2025-11-17 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pattern_to_match', models.CharField(max_length=255, unique=True)),
                ('explanation', models.TextField()),
                ('recommendation', models.CharField(choices=[('INVESTIGATE', 'Investigate'), ('BLOCK_IP', 'Block IP Address'), ('IGNORE', 'Ignore'), ('FYI', 'For Your Information')], default='INVESTIGATE', max_length=20)),
                ('llm_generated', models.BooleanField(default=False, help_text='Whether this rule was auto-generated by LLM')),
                ('solution', models.TextField(blank=True, default='', help_text='Step-by-step solution commands generated by LLM')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=22)),
                ('ssh_key_deployed', models.BooleanField(default=False, help_text='Whether SSH key has been deployed')),
                ('ssh_key_deployed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Link Connection',
                'verbose_name_plural': 'Link Connections',
            },
        ),
        migrations.CreateModel(
            name='MonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_interval_seconds', models.IntegerField(default=60, help_text='Seconds between metric collections')),
                ('adaptive_collection_enabled', models.BooleanField(default=False, help_text='Enable adaptive collection frequency')),
                ('anomaly_detection_interval', models.IntegerField(default=15, help_text='Collection interval when anomaly detected (seconds)')),
                ('enabled', models.BooleanField(default=True)),
                ('use_adtk', models.BooleanField(default=True, help_text='Use ADTK (primary) vs IsolationForest (fallback)')),
                ('use_isolation_forest', models.BooleanField(default=False, help_text='Use IsolationForest (fallback)')),
                ('contamination', models.FloatField(default=0.1, help_text='Expected proportion of anomalies (0.0-0.5)')),
                ('window_size', models.IntegerField(default=100, help_text='Number of recent metrics for training')),
                ('adtk_threshold_factor', models.FloatField(default=2.0, help_text='Threshold factor for ADTK detectors')),
                ('adtk_window_size', models.IntegerField(default=30, help_text='Window size for ADTK time-series analysis')),
                ('cpu_threshold', models.FloatField(default=90.0)),
                ('memory_threshold', models.FloatField(default=90.0)),
                ('disk_threshold', models.FloatField(default=90.0)),
                ('use_llm_explanation', models.BooleanField(default=True, help_text='Always generate LLM explanations for anomalies')),
                ('retention_period_days', models.IntegerField(default=30, help_text='Days to keep raw metrics before deletion')),
                ('aggregation_enabled', models.BooleanField(default=True, help_text='Enable metric aggregation')),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_config', to='core.server')),
            ],
            options={
                'verbose_name': 'Monitoring Configuration',
                'verbose_name_plural': 'Monitoring Configurations',
            },
        ),
        migrations.CreateModel(
            name='MonitoredLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=50)),
                ('log_path', models.CharField(max_length=255)),
                ('last_read_offset', models.BigIntegerField(default=0)),
                ('parser_type', models.CharField(choices=[('GENERIC_ERROR', 'Generic Error Log'), ('APACHE_ERROR', 'Apache Error Log'), ('NGINX_ERROR', 'Nginx Error Log'), ('CRON_STATUS', 'Cron Status Log')], default='GENERIC_ERROR', max_length=20)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.server')),
            ],
            options={
                'verbose_name': 'Track Activity',
                'verbose_name_plural': 'Track Activities',
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cpu_percent', models.FloatField()),
                ('cpu_count', models.IntegerField(blank=True, help_text='Logical CPU count', null=True)),
                ('physical_cpu_count', models.IntegerField(blank=True, help_text='Physical CPU cores', null=True)),
                ('cpu_load_avg_1m', models.FloatField(blank=True, null=True)),
                ('cpu_load_avg_5m', models.FloatField(blank=True, null=True)),
                ('cpu_load_avg_15m', models.FloatField(blank=True, null=True)),
                ('memory_total', models.BigIntegerField()),
                ('memory_available', models.BigIntegerField()),
                ('memory_percent', models.FloatField()),
                ('memory_used', models.BigIntegerField()),
                ('memory_buffers', models.BigIntegerField(blank=True, null=True)),
                ('memory_cached', models.BigIntegerField(blank=True, null=True)),
                ('memory_shared', models.BigIntegerField(blank=True, null=True)),
                ('swap_total', models.BigIntegerField(blank=True, null=True)),
                ('swap_used', models.BigIntegerField(blank=True, null=True)),
                ('swap_percent', models.FloatField(blank=True, null=True)),
                ('disk_usage', models.JSONField(default=dict)),
                ('network_io', models.JSONField(default=dict)),
                ('network_connections', models.IntegerField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.server')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metric_type', models.CharField(max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('anomaly_score', models.FloatField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('llm_generated', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.server')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.systemmetric')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='The client IP address, if available.', null=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_count', models.PositiveIntegerField(default=1)),
                ('is_notified', models.BooleanField(default=False)),
                ('monitored_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.monitoredlog')),
            ],
            options={
                'indexes': [models.Index(fields=['monitored_log', 'message'], name='core_logeve_monitor_8b184b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AggregatedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('cpu_avg', models.FloatField(blank=True, null=True)),
                ('cpu_min', models.FloatField(blank=True, null=True)),
                ('cpu_max', models.FloatField(blank=True, null=True)),
                ('memory_avg', models.FloatField(blank=True, null=True)),
                ('memory_min', models.FloatField(blank=True, null=True)),
                ('memory_max', models.FloatField(blank=True, null=True)),
                ('disk_avg', models.FloatField(blank=True, null=True)),
                ('disk_min', models.FloatField(blank=True, null=True)),
                ('disk_max', models.FloatField(blank=True, null=True)),
                ('metric_count', models.IntegerField(default=0, help_text='Number of raw metrics aggregated')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_metrics', to='core.server')),
            ],
            options={
                'indexes': [models.Index(fields=['server', 'aggregation_type', '-timestamp'], name='core_aggreg_server__f02d3a_idx')],
                'unique_together': {('server', 'aggregation_type', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('service_type', models.CharField(default='systemd', max_length=50)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('process_id', models.CharField(blank=True, max_length=50, null=True)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.server')),
            ],
            options={
                'indexes': [models.Index(fields=['server', 'status'], name='core_servic_server__db1f65_idx'), models.Index(fields=['last_checked'], name='core_servic_last_ch_cbfabc_idx')],
                'unique_together': {('server', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='systemmetric',
            index=models.Index(fields=['server', '-timestamp'], name='core_system_server__ed442c_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['server', '-timestamp'], name='core_anomal_server__c789e1_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['severity', '-timestamp'], name='core_anomal_severit_9bb6eb_idx'),
        ),
    ]
