# Generated by Django 5.2.8 on 2025-11-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='custom', max_length=50)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=465)),
                ('use_tls', models.BooleanField(default=False)),
                ('smtp_username', models.EmailField(max_length=254)),
                ('smtp_password', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('alert_recipients', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
