# Generated by Django 5.2.8 on 2025-11-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailalertconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringconfig',
            name='cpu_threshold',
            field=models.FloatField(default=80.0, help_text='CPU usage threshold (%)'),
        ),
        migrations.AlterField(
            model_name='monitoringconfig',
            name='disk_threshold',
            field=models.FloatField(default=90.0, help_text='Disk usage threshold (%)'),
        ),
        migrations.AlterField(
            model_name='monitoringconfig',
            name='memory_threshold',
            field=models.FloatField(default=90.0, help_text='Memory usage threshold (%)'),
        ),
    ]
