# Generated by Django 5.2.7 on 2025-12-10 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_monitoringconfig_cpu_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Machine-readable key (e.g., 'view_dashboard')", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Human-readable label (e.g., 'View Dashboard')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privilege',
                'verbose_name_plural': 'Privileges',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of this role's responsibilities")),
                ('is_protected', models.BooleanField(default=False, help_text='Protected roles cannot be renamed or deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='monitoringconfig',
            name='alert_suppressed',
            field=models.BooleanField(default=False, help_text='Suppress alerts for this server'),
        ),
        migrations.AddField(
            model_name='monitoringconfig',
            name='monitoring_suspended',
            field=models.BooleanField(default=False, help_text='Suspend monitoring for this server'),
        ),
        migrations.AddField(
            model_name='service',
            name='monitoring_enabled',
            field=models.BooleanField(default=False, help_text='Whether monitoring is enabled for this service'),
        ),
        migrations.CreateModel(
            name='UserACL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_dashboard', models.BooleanField(default=True, help_text='[DEPRECATED] Use role privileges')),
                ('can_edit_thresholds', models.BooleanField(default=False, help_text='[DEPRECATED] Use role privileges')),
                ('can_halt_monitoring', models.BooleanField(default=False, help_text='[DEPRECATED] Use role privileges')),
                ('can_mute_notifications', models.BooleanField(default=False, help_text='[DEPRECATED] Use role privileges')),
                ('can_add_server', models.BooleanField(default=False, help_text='[DEPRECATED] Use role privileges')),
                ('can_edit_server', models.BooleanField(default=False, help_text='[DEPRECATED] Use role privileges')),
                ('can_delete_server', models.BooleanField(default=False, help_text='[DEPRECATED] Use role privileges')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, help_text="Role that defines this user's permissions", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acl', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User ACL',
                'verbose_name_plural': 'User ACLs',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('CPU', 'CPU'), ('Memory', 'Memory'), ('Disk', 'Disk'), ('CONNECTION', 'Connection'), ('SERVICE', 'Service')], max_length=20)),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('resolved', 'Resolved')], default='triggered', max_length=20)),
                ('value', models.FloatField(help_text='Current metric value')),
                ('threshold', models.FloatField(help_text='Threshold value')),
                ('message', models.TextField()),
                ('recipients', models.TextField(help_text='Comma-separated list of email recipients')),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_history', to='core.server')),
            ],
            options={
                'verbose_name': 'Alert History',
                'verbose_name_plural': 'Alert History',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['server', '-sent_at'], name='core_alerth_server__693259_idx'), models.Index(fields=['status', '-sent_at'], name='core_alerth_status_d66174_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_privileges', to='core.privilege')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_privileges', to='core.role')),
            ],
            options={
                'verbose_name': 'Role Privilege',
                'verbose_name_plural': 'Role Privileges',
                'unique_together': {('role', 'privilege')},
            },
        ),
    ]
