# Generated by Django 5.2.7 on 2025-12-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_privilege_role_alter_useracl_can_add_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='suppress_alerts',
            field=models.BooleanField(default=False, help_text='Whether to suppress email alerts for this server'),
        ),
        migrations.AddField(
            model_name='server',
            name='suspend_monitoring',
            field=models.BooleanField(default=False, help_text='Whether to suspend monitoring for this server'),
        ),
    ]
