# Generated by Django 5.2.7 on 2025-12-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_monitoringconfig_cpu_threshold_and_more'),
    ]

    # NOTE: These two fields (server.suppress_alerts, server.suspend_monitoring)
    # are already added by the sibling migration 0004_add_server_fields, which
    # Django applies first on a fresh database (both depend on 0003). Re-adding
    # them here raised "column already exists". This migration is kept as a
    # no-op so it stays in the graph (0017_merge depends on it) without
    # duplicating the columns.
    operations = []
