# Generated by Django 5.2.8 on 2025-12-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_io_rate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetric',
            name='disk_read_bytes_total',
            field=models.BigIntegerField(blank=True, help_text='Cumulative disk read bytes (all disks)', null=True),
        ),
        migrations.AddField(
            model_name='systemmetric',
            name='disk_write_bytes_total',
            field=models.BigIntegerField(blank=True, help_text='Cumulative disk write bytes (all disks)', null=True),
        ),
    ]
