# Generated by Django 5.2.8 on 2025-12-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_disk_io_total_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetric',
            name='net_utilization_recv',
            field=models.FloatField(blank=True, help_text='Network receive utilization % (based on NIC max speed)', null=True),
        ),
        migrations.AddField(
            model_name='systemmetric',
            name='net_utilization_sent',
            field=models.FloatField(blank=True, help_text='Network send utilization % (based on NIC max speed)', null=True),
        ),
        migrations.AddField(
            model_name='systemmetric',
            name='nic_max_speed_bits',
            field=models.BigIntegerField(blank=True, help_text='Total NIC max speed in bits/second (all interfaces)', null=True),
        ),
    ]
