# Generated by Django 5.2.8 on 2025-12-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_network_utilization_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringconfig',
            name='disk_io_threshold',
            field=models.FloatField(default=1000.0, help_text='Disk I/O threshold (MB/s)'),
        ),
        migrations.AddField(
            model_name='monitoringconfig',
            name='monitored_disks',
            field=models.JSONField(default=list, help_text="List of disk mount points to monitor (e.g., ['/', '/home'])"),
        ),
        migrations.AddField(
            model_name='monitoringconfig',
            name='network_io_threshold',
            field=models.FloatField(default=1000.0, help_text='Network I/O threshold (MB/s)'),
        ),
    ]
