# Generated by Django 5.2.7 on 2025-12-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_server_toggles'),
        ('core', '0016_add_server_heartbeat'),
    ]

    operations = [
    ]
