# Generated by Django 5.2.7 on 2025-12-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20251217_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailalertconfig',
            name='to_email',
            field=models.EmailField(blank=True, help_text='Recipient email address for alerts (comma-separated for multiple)', max_length=254),
        ),
    ]
