# Generated by Django 5.2.7 on 2025-12-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_to_email_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serverheartbeat',
            new_name='core_server_server__0b8cbf_idx',
            old_name='core_server_server__idx',
        ),
        migrations.RenameIndex(
            model_name='serverheartbeat',
            new_name='core_server_last_he_2e7983_idx',
            old_name='core_server_last_hea_idx',
        ),
        # Only add top_processes - system_uptime_seconds already exists in database
        migrations.AddField(
            model_name='systemmetric',
            name='top_processes',
            field=models.JSONField(blank=True, help_text="Top processes by CPU/Memory at collection time. Format: {'cpu': [...], 'memory': [...]}", null=True),
        ),
    ]
