# Generated by Django 5.2.8 on 2025-12-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_core_server_server__idx_core_server_server__0b8cbf_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE core_monitoredlog ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT TRUE;",
            reverse_sql="ALTER TABLE core_monitoredlog DROP COLUMN IF EXISTS enabled;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE core_monitoredlog ADD COLUMN IF NOT EXISTS last_scan_time TIMESTAMP NULL;",
            reverse_sql="ALTER TABLE core_monitoredlog DROP COLUMN IF EXISTS last_scan_time;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE core_monitoredlog ADD COLUMN IF NOT EXISTS scan_from_days INTEGER DEFAULT 1;",
            reverse_sql="ALTER TABLE core_monitoredlog DROP COLUMN IF EXISTS scan_from_days;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE core_monitoredlog ADD COLUMN IF NOT EXISTS service_type VARCHAR(20) DEFAULT 'custom';",
            reverse_sql="ALTER TABLE core_monitoredlog DROP COLUMN IF EXISTS service_type;",
        ),
        migrations.AlterField(
            model_name='monitoredlog',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable log troubleshooting for this log'),
        ),
        migrations.AlterField(
            model_name='monitoredlog',
            name='last_scan_time',
            field=models.DateTimeField(blank=True, help_text='Last time logs were scanned', null=True),
        ),
        migrations.AlterField(
            model_name='monitoredlog',
            name='scan_from_days',
            field=models.IntegerField(default=1, help_text='Start scanning from this many days ago (default: 1 day)'),
        ),
        migrations.AlterField(
            model_name='monitoredlog',
            name='service_type',
            field=models.CharField(choices=[('apache', 'Apache'), ('nginx', 'Nginx'), ('exim', 'Exim'), ('postfix', 'Postfix'), ('mysql', 'MySQL'), ('mariadb', 'MariaDB'), ('custom', 'Custom App')], default='custom', help_text='Service type for automatic log path detection', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitoredlog',
            name='parser_type',
            field=models.CharField(choices=[('GENERIC_ERROR', 'Generic Error Log'), ('APACHE_ERROR', 'Apache Error Log'), ('NGINX_ERROR', 'Nginx Error Log'), ('CRON_STATUS', 'Cron Status Log'), ('EXIM_ERROR', 'Exim Error Log'), ('POSTFIX_ERROR', 'Postfix Error Log'), ('MYSQL_ERROR', 'MySQL Error Log'), ('MARIADB_ERROR', 'MariaDB Error Log'), ('CUSTOM_APP', 'Custom Application')], default='GENERIC_ERROR', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='monitoredlog',
            unique_together={('server', 'log_path')},
        ),
    ]
