# Generated by Django 5.2.8 on 2025-12-22 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def check_and_add_uptime_field(apps, schema_editor):
    """Check if system_uptime_seconds column exists before adding it"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='core_systemmetric' AND column_name='system_uptime_seconds'
        """)
        if not cursor.fetchone():
            # Column doesn't exist, add it
            schema_editor.add_field(
                apps.get_model('core', 'SystemMetric'),
                models.BigIntegerField(blank=True, help_text='System uptime in seconds (time since last boot)', null=True),
                name='system_uptime_seconds'
            )


def reverse_check(apps, schema_editor):
    """Reverse operation - no-op since we're checking conditionally"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_monitoredlog_enabled_monitoredlog_last_scan_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Skip AddField for system_uptime_seconds since it already exists
        # Only create the new models
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Agent version string (e.g., 'v2.4.1')", max_length=50)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Last time this version was reported')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_versions', to='core.server')),
            ],
            options={
                'verbose_name': 'Agent Version',
                'verbose_name_plural': 'Agent Versions',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['-last_seen'], name='core_agentv_last_se_f0c568_idx'), models.Index(fields=['version'], name='core_agentv_version_811a26_idx')],
                'unique_together': {('server', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Email address used for login attempt', max_length=255)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the login attempt')),
                ('location', models.CharField(blank=True, help_text="Geographical location (e.g., 'San Francisco, US')", max_length=255, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], help_text='Login attempt status', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the login attempt occurred')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Activity',
                'verbose_name_plural': 'Login Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_logina_timesta_c4b418_idx'), models.Index(fields=['status', '-timestamp'], name='core_logina_status_42b256_idx'), models.Index(fields=['email', '-timestamp'], name='core_logina_email_3bdf66_idx')],
            },
        ),
    ]
