# Generated by Django 5.2.7 on 2025-12-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_systemmetric_system_uptime_seconds_agentversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_timezone', models.CharField(default='UTC', help_text="Timezone for displaying all timestamps (e.g., 'Asia/Kolkata', 'America/New_York')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Configuration',
                'verbose_name_plural': 'Application Configuration',
            },
        ),
    ]
