# Generated by Django 5.2.7 on 2026-01-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_app_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='language',
            field=models.CharField(choices=[('en', 'English')], default='en', help_text='Application language', max_length=10),
        ),
    ]
