# Generated by Django 5.2.7 on 2026-01-02 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_language_to_app_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('UPTIME', 'Uptime'), ('CPU', 'CPU'), ('MEMORY', 'Memory'), ('DISK', 'Disk'), ('NETWORK', 'Network'), ('RESPONSE_TIME', 'Response Time'), ('ERROR_RATE', 'Error Rate')], help_text='Type of metric for this SLI', max_length=50, unique=True)),
                ('calculation_method', models.CharField(default='percentage', help_text="How to calculate this SLI (e.g., 'percentage', 'average', 'percentile')", max_length=50)),
                ('time_window_days', models.IntegerField(default=7, help_text='Default time window in days for measurement (7, 30, 90)')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this SLI is enabled')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this SLI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SLI Configuration',
                'verbose_name_plural': 'SLI Configurations',
                'ordering': ['metric_type'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLatencyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency_ms', models.FloatField(help_text='Measured latency in milliseconds')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When measurement was taken')),
                ('success', models.BooleanField(default=True, help_text='Whether measurement succeeded')),
                ('error_message', models.TextField(blank=True, help_text='Error details if measurement failed', null=True)),
                ('measurement_type', models.CharField(choices=[('HTTP', 'HTTP'), ('MYSQL', 'MySQL'), ('OTHER', 'Other')], default='HTTP', help_text='How latency was measured', max_length=20)),
                ('service', models.ForeignKey(help_text='Service for which latency is measured', on_delete=django.db.models.deletion.CASCADE, related_name='latency_measurements', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Latency Measurement',
                'verbose_name_plural': 'Service Latency Measurements',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service', '-timestamp'], name='core_servic_service_72c4b6_idx'), models.Index(fields=['timestamp'], name='core_servic_timesta_e56430_idx')],
            },
        ),
        migrations.CreateModel(
            name='SLIMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('UPTIME', 'Uptime'), ('CPU', 'CPU'), ('MEMORY', 'Memory'), ('DISK', 'Disk'), ('NETWORK', 'Network'), ('RESPONSE_TIME', 'Response Time'), ('ERROR_RATE', 'Error Rate')], help_text='Type of metric', max_length=50)),
                ('time_window_start', models.DateTimeField(help_text='Start of time window for this measurement')),
                ('time_window_end', models.DateTimeField(db_index=True, help_text='End of time window for this measurement')),
                ('sli_value', models.FloatField(help_text='Calculated SLI value')),
                ('slo_target', models.FloatField(help_text='Target value from SLOConfig')),
                ('is_compliant', models.BooleanField(default=False, help_text='Whether sli_value meets SLO target')),
                ('compliance_percentage', models.FloatField(blank=True, help_text='Compliance percentage (e.g., 98.5)', null=True)),
                ('calculated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this measurement was calculated')),
                ('server', models.ForeignKey(help_text='Server for this measurement', on_delete=django.db.models.deletion.CASCADE, related_name='sli_measurements', to='core.server')),
            ],
            options={
                'verbose_name': 'SLI Measurement',
                'verbose_name_plural': 'SLI Measurements',
                'ordering': ['-time_window_end', '-calculated_at'],
                'indexes': [models.Index(fields=['server', 'metric_type', '-time_window_end'], name='core_slimea_server__ab65ae_idx'), models.Index(fields=['server', '-time_window_end'], name='core_slimea_server__c6d80e_idx'), models.Index(fields=['metric_type', '-time_window_end'], name='core_slimea_metric__bd20b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SLOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('UPTIME', 'Uptime'), ('CPU', 'CPU'), ('MEMORY', 'Memory'), ('DISK', 'Disk'), ('NETWORK', 'Network'), ('RESPONSE_TIME', 'Response Time'), ('ERROR_RATE', 'Error Rate')], help_text='Type of metric for this SLO', max_length=50)),
                ('target_value', models.FloatField(help_text='Target value (e.g., 99.9 for 99.9% uptime, 200 for 200ms response time)')),
                ('target_operator', models.CharField(choices=[('gte', 'Greater than or equal (≥)'), ('lte', 'Less than or equal (≤)'), ('eq', 'Equal (=)')], default='gte', help_text="Comparison operator (e.g., 'gte' for uptime >= 99.9%)", max_length=10)),
                ('time_window_days', models.IntegerField(blank=True, help_text='Time window in days for this SLO (overrides SLIConfig default if set)', null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this SLO is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(blank=True, help_text='Server for this SLO override (null for global default)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slo_configs', to='core.server')),
            ],
            options={
                'verbose_name': 'SLO Configuration',
                'verbose_name_plural': 'SLO Configurations',
                'ordering': ['metric_type'],
                'indexes': [models.Index(fields=['server', 'metric_type'], name='core_slocon_server__ab210c_idx'), models.Index(fields=['metric_type'], name='core_slocon_metric__bfccc4_idx')],
                'unique_together': {('server', 'metric_type')},
            },
        ),
    ]
