# Generated by Django 5.2.7 on 2026-01-02 10:52

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    """Populate initial SLIConfig records and global SLO defaults"""
    SLIConfig = apps.get_model('core', 'SLIConfig')
    SLOConfig = apps.get_model('core', 'SLOConfig')
    
    # Create SLIConfig records for each metric type
    sli_configs = [
        {
            'metric_type': 'UPTIME',
            'calculation_method': 'percentage',
            'time_window_days': 7,
            'enabled': True,
            'description': 'Server uptime percentage over time window'
        },
        {
            'metric_type': 'CPU',
            'calculation_method': 'average',
            'time_window_days': 7,
            'enabled': True,
            'description': 'Average CPU usage percentage'
        },
        {
            'metric_type': 'MEMORY',
            'calculation_method': 'average',
            'time_window_days': 7,
            'enabled': True,
            'description': 'Average memory usage percentage'
        },
        {
            'metric_type': 'DISK',
            'calculation_method': 'average',
            'time_window_days': 7,
            'enabled': True,
            'description': 'Average disk usage percentage'
        },
        {
            'metric_type': 'NETWORK',
            'calculation_method': 'average',
            'time_window_days': 7,
            'enabled': True,
            'description': 'Average network utilization percentage'
        },
        {
            'metric_type': 'RESPONSE_TIME',
            'calculation_method': 'average',
            'time_window_days': 7,
            'enabled': True,
            'description': 'Average response time in milliseconds (for monitored services only)'
        },
        {
            'metric_type': 'ERROR_RATE',
            'calculation_method': 'percentage',
            'time_window_days': 7,
            'enabled': True,
            'description': 'Error rate percentage (if error tracking available)'
        },
    ]
    
    for config_data in sli_configs:
        SLIConfig.objects.get_or_create(
            metric_type=config_data['metric_type'],
            defaults=config_data
        )
    
    # Create global default SLOConfig records (server=None)
    slo_configs = [
        {
            'server': None,
            'metric_type': 'UPTIME',
            'target_value': 99.9,
            'target_operator': 'gte',
            'time_window_days': 7,
            'enabled': True
        },
        {
            'server': None,
            'metric_type': 'CPU',
            'target_value': 80.0,
            'target_operator': 'lte',
            'time_window_days': 7,
            'enabled': True
        },
        {
            'server': None,
            'metric_type': 'MEMORY',
            'target_value': 85.0,
            'target_operator': 'lte',
            'time_window_days': 7,
            'enabled': True
        },
        {
            'server': None,
            'metric_type': 'DISK',
            'target_value': 90.0,
            'target_operator': 'lte',
            'time_window_days': 7,
            'enabled': True
        },
        {
            'server': None,
            'metric_type': 'NETWORK',
            'target_value': 80.0,
            'target_operator': 'lte',
            'time_window_days': 7,
            'enabled': True
        },
        {
            'server': None,
            'metric_type': 'RESPONSE_TIME',
            'target_value': 200.0,
            'target_operator': 'lte',
            'time_window_days': 7,
            'enabled': True
        },
        {
            'server': None,
            'metric_type': 'ERROR_RATE',
            'target_value': 1.0,
            'target_operator': 'lte',
            'time_window_days': 7,
            'enabled': True
        },
    ]
    
    for config_data in slo_configs:
        SLOConfig.objects.get_or_create(
            server=config_data['server'],
            metric_type=config_data['metric_type'],
            defaults=config_data
        )


def reverse_populate_initial_data(apps, schema_editor):
    """Reverse migration - remove initial data"""
    SLIConfig = apps.get_model('core', 'SLIConfig')
    SLOConfig = apps.get_model('core', 'SLOConfig')
    
    # Remove SLIConfig records
    SLIConfig.objects.all().delete()
    
    # Remove global SLOConfig records (server=None)
    SLOConfig.objects.filter(server=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sliconfig_systemmetric_system_uptime_seconds_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data, reverse_populate_initial_data),
    ]
