# Generated by Django 5.2.8 on 2026-01-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_populate_sli_slo_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='auto_detected',
            field=models.BooleanField(default=False, help_text='Whether this service was auto-detected from port scan'),
        ),
        migrations.AddField(
            model_name='service',
            name='bind_address',
            field=models.CharField(blank=True, help_text='IP address the service is bound to (e.g., 0.0.0.0, 127.0.0.1)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicelatencymeasurement',
            name='measurement_type',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('TCP', 'TCP'), ('MYSQL', 'MySQL'), ('SSH_LOCAL', 'SSH Local (localhost-bound)'), ('OTHER', 'Other')], default='HTTP', help_text='How latency was measured', max_length=20),
        ),
    ]
