# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_service_bind_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='logevent',
            name='ip_counts',
            field=models.JSONField(
                blank=True,
                help_text='Map of client IP to request count, e.g. {"1.2.3.4": 100, "5.6.7.8": 3}',
                null=True,
            ),
        ),
    ]
