# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_logevent_ip_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='log_retention_days',
            field=models.PositiveSmallIntegerField(
                choices=[(7, '7 days'), (15, '15 days'), (30, '30 days')],
                default=30,
                help_text='Keep Logs Analysis events for this many days; older events are deleted.',
            ),
        ),
    ]
