# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_appconfig_log_retention_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.CharField(help_text='Slack Incoming Webhook URL (starts with https://hooks.slack.com/)', max_length=500)),
                ('channel', models.CharField(blank=True, help_text='Channel to send messages to (e.g., #alerts or @username). Optional if webhook already specifies channel.', max_length=100)),
                ('username', models.CharField(blank=True, help_text='Bot username to display in Slack (optional)', max_length=100)),
                ('icon_emoji', models.CharField(blank=True, default=':warning:', help_text='Emoji icon for bot messages (e.g., :robot_face:, :warning:)', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
