# Generated by Django 5.2.14 on 2026-06-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alerthistory_process_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetric',
            name='system_uptime_seconds',
            field=models.BigIntegerField(blank=True, help_text='System uptime in seconds (time since last boot)', null=True),
        ),
    ]
