# Generated by Django 5.2.14 on 2026-06-01 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_reconcile_system_uptime_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest of the agent token (the raw token is never stored)', max_length=64, unique=True)),
                ('token_prefix', models.CharField(blank=True, help_text='First few characters of the token, for identification only', max_length=12)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this token is currently accepted by the ingest API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time a valid push was received with this token', null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, help_text='Source IP of the last accepted push', null=True)),
                ('server', models.OneToOneField(help_text='The monitored server this token authenticates', on_delete=django.db.models.deletion.CASCADE, related_name='agent_credential', to='core.server')),
            ],
            options={
                'verbose_name': 'Agent Credential',
                'verbose_name_plural': 'Agent Credentials',
            },
        ),
    ]
