# Generated by Django 5.2.14 on 2026-06-01 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_agent_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheticCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this check', max_length=150)),
                ('check_type', models.CharField(choices=[('HTTP', 'HTTP / HTTPS'), ('TCP', 'TCP Port')], default='HTTP', max_length=10)),
                ('url', models.URLField(blank=True, help_text='For HTTP checks, e.g. https://example.com/health', max_length=500)),
                ('method', models.CharField(default='GET', help_text='HTTP method (GET or HEAD)', max_length=10)),
                ('expected_status', models.CharField(default='200-399', help_text="Accepted status codes: e.g. '200', '200,301', or a range '200-399'", max_length=100)),
                ('expected_substring', models.CharField(blank=True, help_text='Optional text that must appear in the response body', max_length=255)),
                ('verify_tls', models.BooleanField(default=True, help_text='Verify the TLS certificate for HTTPS checks')),
                ('host', models.CharField(blank=True, help_text='For TCP checks, hostname or IP', max_length=255)),
                ('port', models.IntegerField(blank=True, help_text='For TCP checks, port number', null=True)),
                ('timeout_seconds', models.IntegerField(default=10)),
                ('interval_seconds', models.IntegerField(default=60, help_text='How often to run this check')),
                ('enabled', models.BooleanField(default=True)),
                ('alert_on_failure', models.BooleanField(default=True)),
                ('failure_threshold', models.IntegerField(default=2, help_text='Consecutive failures before the check is marked DOWN and an alert fires')),
                ('last_status', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('consecutive_successes', models.IntegerField(default=0)),
                ('last_state_change_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synthetic_checks', to='core.server')),
            ],
            options={
                'verbose_name': 'Synthetic Check',
                'verbose_name_plural': 'Synthetic Checks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyntheticCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('synthetic_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.syntheticcheck')),
            ],
            options={
                'verbose_name': 'Synthetic Check Result',
                'verbose_name_plural': 'Synthetic Check Results',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['synthetic_check', '-timestamp'], name='core_synthe_synthet_334707_idx')],
            },
        ),
    ]
