# Generated by Django 5.2.14 on 2026-06-01 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_synthetic_checks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityMonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Run security detection')),
                ('alert_enabled', models.BooleanField(default=True, help_text='Send email/Slack alerts for new security events')),
                ('window_minutes', models.IntegerField(default=10, help_text='Look-back window for correlating login events')),
                ('brute_force_ip_threshold', models.IntegerField(default=8, help_text='Failed logins from one IP within the window before flagging brute force')),
                ('account_failure_threshold', models.IntegerField(default=5, help_text='Failed logins for one account within the window before flagging a spike')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Monitor Configuration',
                'verbose_name_plural': 'Security Monitor Configuration',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BRUTE_FORCE', 'Brute-force login attempts'), ('LOGIN_FAILURE_SPIKE', 'Login failure spike (account)'), ('SUCCESS_AFTER_FAILURES', 'Successful login after repeated failures')], max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('target_email', models.CharField(blank=True, help_text='Account targeted, if applicable', max_length=255)),
                ('event_count', models.IntegerField(default=1, help_text='Number of contributing observations')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['status', '-last_seen'], name='core_securi_status_c2a4b2_idx'), models.Index(fields=['event_type', '-last_seen'], name='core_securi_event_t_7b8bbd_idx'), models.Index(fields=['source_ip'], name='core_securi_source__e4f365_idx')],
            },
        ),
    ]
