# Generated by Django 5.2.14 on 2026-06-01 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_security_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('key', models.SlugField(help_text="Machine key used when pushing values, e.g. 'signups_per_hour'", max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, help_text="Display unit, e.g. '/hr', '$', '%'", max_length=30)),
                ('description', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('higher_better', 'Higher is better'), ('lower_better', 'Lower is better')], default='higher_better', max_length=15)),
                ('warning_threshold', models.FloatField(blank=True, help_text='Value at which the KPI is in warning', null=True)),
                ('critical_threshold', models.FloatField(blank=True, help_text='Value at which the KPI is critical', null=True)),
                ('alert_enabled', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('last_value_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business KPI',
                'verbose_name_plural': 'Business KPIs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingest_token_hash', models.CharField(blank=True, max_length=64)),
                ('ingest_token_prefix', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Monitor Configuration',
                'verbose_name_plural': 'Business Monitor Configuration',
            },
        ),
        migrations.CreateModel(
            name='BusinessKPIValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.FloatField()),
                ('source', models.CharField(choices=[('api', 'API'), ('manual', 'Manual')], default='api', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.businesskpi')),
            ],
            options={
                'verbose_name': 'Business KPI Value',
                'verbose_name_plural': 'Business KPI Values',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['kpi', '-timestamp'], name='core_busine_kpi_id_bd1956_idx')],
            },
        ),
    ]
