# Generated by Django 5.2.14 on 2026-06-02 08:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_business_kpis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(blank=True, help_text='Container ID', max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(default='running', help_text='running, exited, paused, ...', max_length=30)),
                ('status_text', models.CharField(blank=True, help_text="e.g. 'Up 3 hours'", max_length=200)),
                ('ports', models.CharField(blank=True, max_length=300)),
                ('monitoring_enabled', models.BooleanField(default=False)),
                ('auto_detected', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='core.server')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
                'ordering': ['server__name', 'name'],
                'indexes': [models.Index(fields=['server', 'state'], name='core_contai_server__67ab6c_idx')],
                'unique_together': {('server', 'name')},
            },
        ),
    ]
