# Generated by Django 5.2.14 on 2026-06-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracl',
            name='dashboard_view',
            field=models.CharField(choices=[('operations', 'Operations'), ('executive', 'Executive')], default='operations', help_text='Which dashboard perspective this user sees (Operations or Executive)', max_length=20),
        ),
    ]
