# Generated by Django 5.2.14 on 2026-06-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_dashboard_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerthistory',
            name='alert_type',
            field=models.CharField(choices=[('CPU', 'CPU'), ('Memory', 'Memory'), ('Disk', 'Disk'), ('CONNECTION', 'Connection'), ('SERVICE', 'Service'), ('CONTAINER', 'Container')], max_length=20),
        ),
    ]
