# Generated by Django 5.2.14 on 2026-06-03 05:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_container_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='server',
            field=models.ForeignKey(blank=True, help_text='Monitored server this event relates to (for SSH/host events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='core.server'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('BRUTE_FORCE', 'Brute-force login attempts'), ('LOGIN_FAILURE_SPIKE', 'Login failure spike (account)'), ('SUCCESS_AFTER_FAILURES', 'Successful login after repeated failures'), ('SSH_BRUTE_FORCE', 'SSH brute-force on a server')], max_length=40),
        ),
        migrations.CreateModel(
            name='SSHAuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_ip', models.CharField(blank=True, max_length=64)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('success', models.BooleanField(default=False)),
                ('raw', models.CharField(blank=True, max_length=300)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_auth_events', to='core.server')),
            ],
            options={
                'verbose_name': 'SSH Auth Event',
                'verbose_name_plural': 'SSH Auth Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['server', '-timestamp'], name='core_sshaut_server__0755a0_idx'), models.Index(fields=['source_ip'], name='core_sshaut_source__f3f6e5_idx'), models.Index(fields=['success', '-timestamp'], name='core_sshaut_success_c31749_idx')],
            },
        ),
    ]
