# Generated by Django 5.2.14 on 2026-06-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_ssh_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_vcpu_month', models.FloatField(blank=True, help_text='Cost of 1 vCPU per month', null=True)),
                ('price_per_gb_month', models.FloatField(blank=True, help_text='Cost of 1 GB RAM per month', null=True)),
                ('currency', models.CharField(default='$', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
    ]
