# Generated by Django 5.2.14 on 2026-06-05 06:45

from django.db import migrations, models


def disable_llm_explanation(apps, schema_editor):
    # The deterministic explanation now replaces the LLM one; turn off the LLM
    # dependency for existing servers (the default-change only affects new rows).
    MonitoringConfig = apps.get_model('core', 'MonitoringConfig')
    MonitoringConfig.objects.update(use_llm_explanation=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_ceo_no_impersonate'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringconfig',
            name='anomaly_sensitivity',
            field=models.CharField(choices=[('OFF', 'Off'), ('LOW', 'Low'), ('BALANCED', 'Balanced'), ('HIGH', 'High')], default='BALANCED', help_text="Anomaly detection sensitivity. 'Off' disables detection for this server.", max_length=10),
        ),
        migrations.AlterField(
            model_name='monitoringconfig',
            name='use_llm_explanation',
            field=models.BooleanField(default=False, help_text='Optionally add an LLM explanation on top of the built-in deterministic one'),
        ),
        migrations.RunPython(disable_llm_explanation, migrations.RunPython.noop),
    ]
