# Generated by Django 5.2.14 on 2026-06-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_monitoringconfig_anomaly_sensitivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetric',
            name='ipc_stats',
            field=models.JSONField(blank=True, help_text='SysV IPC / POSIX shared-memory summary for leak detection. Keys: shm_segments, shm_bytes, shm_orphaned, shm_orphaned_bytes, sem_arrays, msg_queues, msg_bytes, devshm_bytes.', null=True),
        ),
    ]
