# Generated by Django 5.2.14 on 2026-06-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_systemmetric_ipc_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='runtime',
            field=models.CharField(default='docker', help_text='Container runtime: docker, podman, or containerd', max_length=20),
        ),
    ]
