# Generated by Django 5.2.14 on 2026-06-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_container_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='inspect_at',
            field=models.DateTimeField(blank=True, help_text='When the inspect summary was last collected', null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='inspect_data',
            field=models.JSONField(blank=True, help_text='Compact, sanitized `inspect` summary (config/mounts/networks/env-redacted) from the agent', null=True),
        ),
    ]
