# Generated by Django 5.2.14 on 2026-06-08 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_container_inspect_at_container_inspect_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerthistory',
            name='admin_note',
            field=models.TextField(blank=True, default='', help_text="Admin's note / reason recorded when resolving"),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='admin_note',
            field=models.TextField(blank=True, default='', help_text="Admin's note / reason recorded when resolving"),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL),
        ),
    ]
