# Generated by Django 5.2.14 on 2026-06-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alerthistory_admin_note_alerthistory_resolved_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingConfig',
        ),
    ]
