# Generated by Django 5.2.14 on 2026-06-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_delete_pricingconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='port',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_key_deployed',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_key_deployed_at',
        ),
    ]
