# Generated by Django 5.2.14 on 2026-06-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_server_port_remove_server_ssh_key_deployed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetric',
            name='disk_hardware',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
