# Generated by Django 5.2.14 on 2026-06-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_systemmetric_disk_hardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='recovered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
