# Generated by Django 5.2.14 on 2026-06-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_anomaly_recovered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='data_retention_days',
            field=models.PositiveSmallIntegerField(default=60, help_text='Keep collected data (metrics, incidents, logs) for this many days; older data is pruned automatically. Min 7, max 365.'),
        ),
    ]
