# Generated by Django 5.2.14 on 2026-06-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_appconfig_data_retention_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringconfig',
            name='adaptive_collection_enabled',
        ),
        migrations.RemoveField(
            model_name='monitoringconfig',
            name='anomaly_detection_interval',
        ),
    ]
