# Generated by Django 5.2.14 on 2026-06-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_monitoringconfig_adaptive_collection_enabled_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisRule',
        ),
        migrations.AlterUniqueTogether(
            name='monitoredlog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monitoredlog',
            name='server',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='log_retention_days',
        ),
        migrations.DeleteModel(
            name='LogEvent',
        ),
        migrations.DeleteModel(
            name='MonitoredLog',
        ),
    ]
