# Generated by Django 5.2.14 on 2026-06-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_delete_analysisrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerthistory',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', help_text='Severity for routing/grouping (connection down=CRITICAL, threshold/service/container=HIGH, resolved=LOW)', max_length=20),
        ),
    ]
