# Generated by Django 5.2.14 on 2026-06-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alerthistory_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('resource', 'Resource / Performance'), ('availability', 'Availability'), ('security', 'Security'), ('capacity', 'Capacity & Health'), ('business', 'Business')], max_length=20)),
                ('min_severity', models.CharField(choices=[('OFF', 'Off'), ('LOW', 'Low and above'), ('MEDIUM', 'Medium and above'), ('HIGH', 'High and above'), ('CRITICAL', 'Critical only')], default='OFF', help_text='Lowest severity that triggers email for this role+category (OFF = never)', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_routes', to='core.role')),
            ],
            options={
                'verbose_name': 'Alert Routing Rule',
                'verbose_name_plural': 'Alert Routing Rules',
                'ordering': ['role__name', 'category'],
                'unique_together': {('role', 'category')},
            },
        ),
    ]
