# Generated by Django 5.2.14 on 2026-06-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_seed_default_alert_routing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailalertconfig',
            name='to_email',
        ),
    ]
