# Generated by Django 5.2.14 on 2026-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_remove_emailalertconfig_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='base_url',
            field=models.URLField(blank=True, default='', help_text='Public base URL of this instance (used for absolute links in emails/UI).'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='setup_completed',
            field=models.BooleanField(default=False, help_text='True once the first-run setup wizard has created the initial admin.'),
        ),
    ]
