# Generated by Django 5.2.14 on 2026-06-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_appconfig_base_url_appconfig_setup_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detected_via',
            field=models.CharField(blank=True, help_text='Detection provenance', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='display_name',
            field=models.CharField(blank=True, help_text='Friendly UI label; identity stays in name', max_length=150, null=True),
        ),
    ]
