# Generated by Django 5.2.14 on 2026-06-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_service_detected_via_service_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='os_type',
            field=models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('other', 'Other')], db_index=True, default='linux', max_length=10),
        ),
        migrations.AddField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, default='', help_text='Reported OS version string', max_length=200),
        ),
    ]
