# Generated by Django 5.2.14 on 2026-06-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_server_os_type_server_os_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmetric',
            name='server',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.server'),
        ),
    ]
