# Generated by Django 5.2.15 on 2026-06-25 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_systemmetric_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.TextField(blank=True, default='', help_text='Signed license token.')),
                ('licensee', models.CharField(blank=True, default='', max_length=255)),
                ('edition', models.CharField(blank=True, default='', max_length=20)),
                ('max_servers', models.IntegerField(blank=True, null=True)),
                ('expires', models.DateField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'License',
            },
        ),
        migrations.AddField(
            model_name='appconfig',
            name='install_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
