# Generated by Django 5.2.15 on 2026-06-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_license_appconfig_install_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('resource', 'Resource / Performance'), ('availability', 'Availability'), ('security', 'Security'), ('capacity', 'Capacity & Health'), ('business', 'Business')], max_length=20, unique=True)),
                ('min_severity', models.CharField(choices=[('OFF', 'Off'), ('LOW', 'Low and above'), ('MEDIUM', 'Medium and above'), ('HIGH', 'High and above'), ('CRITICAL', 'Critical only')], default='LOW', help_text='Lowest severity that posts this category to Slack (OFF = never)', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slack Routing Rule',
                'verbose_name_plural': 'Slack Routing Rules',
                'ordering': ['category'],
            },
        ),
    ]
