# Generated by Django 5.2.15 on 2026-06-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_slackroutingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracl',
            name='email_alerts_enabled',
            field=models.BooleanField(default=True, help_text='If off, this user is never included in alert emails (a per-user mute), regardless of the role-based routing rules.'),
        ),
    ]
