# Generated by Django 5.2.15 on 2026-07-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_realign_resource_slo_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='slow_consecutive_samples',
            field=models.PositiveSmallIntegerField(default=3, help_text='Consecutive over-threshold samples before a service is flagged slow (anti-flap).'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='slow_latency_threshold_ms',
            field=models.PositiveIntegerField(default=500, help_text="A service is 'slow' when its response time exceeds this many ms (global default; a per-service override lives on the Service)."),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='slow_service_alert_enabled',
            field=models.BooleanField(default=False, help_text='Raise an alert when a monitored service becomes slow (off by default).'),
        ),
        migrations.AddField(
            model_name='service',
            name='last_latency_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_latency_ms',
            field=models.FloatField(blank=True, help_text='Most recent agent-measured response time (ms); NULL if never measured', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_latency_success',
            field=models.BooleanField(blank=True, help_text='Whether the most recent latency probe connected', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='latency_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('ok', 'OK'), ('slow', 'Slow')], default='unknown', help_text='Responsiveness: ok / slow (degraded) / unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='latency_threshold_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Per-service slow threshold (ms); NULL uses the global default', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slow_streak',
            field=models.PositiveSmallIntegerField(default=0, help_text='Consecutive over-threshold samples (anti-flap counter)'),
        ),
    ]
