# Generated by Django 5.2.15 on 2026-07-07 06:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_appconfig_slow_consecutive_samples_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAvailabilitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('up', models.BooleanField(help_text='Whether the service was available at this sample')),
                ('service', models.ForeignKey(help_text='Service this availability sample belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='availability_samples', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Availability Sample',
                'verbose_name_plural': 'Service Availability Samples',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service', '-timestamp'], name='core_servic_service_03e412_idx'), models.Index(fields=['timestamp'], name='core_servic_timesta_7156ae_idx')],
            },
        ),
    ]
