# Generated by Django 5.2.15 on 2026-07-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_serviceavailabilitysample'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='availability_target_pct',
            field=models.FloatField(default=99.0, help_text="Global availability SLO target %: a monitored service is 'degraded' when its 24h availability falls below this (per-service override lives on the Service)."),
        ),
        migrations.AddField(
            model_name='service',
            name='availability_24h_pct',
            field=models.FloatField(blank=True, help_text='Denormalized availability % over the last 24h (from ServiceAvailabilitySample)', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='availability_target_pct',
            field=models.FloatField(blank=True, help_text='Per-service availability SLO target %; NULL uses the global default', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='health_reason',
            field=models.CharField(blank=True, help_text='Which SLO drove the current health state (for the UI tooltip)', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='health_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down')], default='unknown', help_text='Overall health: healthy / degraded / down / unknown', max_length=10),
        ),
    ]
