# Generated by Django 5.2.15 on 2026-07-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_appconfig_availability_target_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slow_alert_enabled',
            field=models.BooleanField(default=False, help_text='Alert + count as an incident when THIS service is slow. Also requires the fleet master (AppConfig.slow_service_alert_enabled) to be on.'),
        ),
    ]
