# Generated by Django 5.2.15 on 2026-07-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_service_slow_alert_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user_label',
            field=models.CharField(blank=True, help_text='Operator-assigned name; overrides the auto-detected label', max_length=100, null=True),
        ),
    ]
