from django.urls import path
from django.contrib.auth import views as auth_views
from core.password_reset_views import CustomPasswordResetView
from . import views

urlpatterns = [
    path("", views.monitoring_dashboard, name="dashboard"),
    path("monitoring/", views.monitoring_dashboard, name="monitoring_dashboard"),
    path("dashboard/", views.monitoring_dashboard, name="dashboard_alt"),
    path("add-server/", views.add_server, name="add_server"),
    path("api/add-server/", views.add_server_api, name="add_server_api"),
    path("servers/", views.server_list, name="server_list"),
    path("server/edit/<int:server_id>/", views.edit_server, name="edit_server"),
    path("server/delete/<int:server_id>/", views.delete_server, name="delete_server"),
    path("remove-server/<int:server_id>/", views.remove_server, name="remove_server"),
    path("api/live-metrics/", views.get_live_metrics, name="live_metrics"),
    path("api/heartbeat/<int:server_id>/", views.heartbeat_api, name="heartbeat_api"),
    path("alert-config/", views.alert_config, name="alert_config"),
    path("alert-config/save/", views.save_alert_config, name="save_alert_config"),
    path("alert-config/clear/", views.clear_alert_config, name="clear_alert_config"),
    path("alert-config/test/", views.test_alert_config, name="test_alert_config"),
    path("api/server/<int:server_id>/thresholds/", views.update_thresholds, name="update_thresholds"),
    path("server/<int:server_id>/anomalies/", views.server_anomalies_log, name="server_anomalies_log"),
    path("server/<int:server_id>/", views.server_details, name="server_details"),
    path("password-reset/", CustomPasswordResetView.as_view(template_name="admin/password_reset.html", email_template_name="admin/password_reset_email.html"), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name="admin/password_reset_done.html"), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name="admin/password_reset_confirm.html"), name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(template_name="admin/password_reset_complete.html"), name="password_reset_complete"),
    path("admin-users/", views.admin_users, name="admin_users"),
    path("admin-users/create/", views.create_admin_user, name="create_admin_user"),
    path("admin-users/edit/<int:user_id>/", views.edit_admin_user, name="edit_admin_user"),
    path("admin-users/delete/<int:user_id>/", views.delete_admin_user, name="delete_admin_user"),
    path("api/admin-users/", views.admin_users_api, name="admin_users_api"),
    path("api/admin-users/create/", views.create_admin_user_api, name="create_admin_user_api"),
    path("api/admin-users/<int:user_id>/", views.admin_user_api, name="admin_user_api"),
    path("alerts/", views.alert_history, name="alert_history"),
    path("api/alert-history/", views.alert_history_api, name="alert_history_api"),
    path("api/alerts/<int:alert_id>/resolve/", views.resolve_alert, name="resolve_alert"),
    path("api/alerts/bulk-resolve/", views.bulk_resolve_alerts, name="bulk_resolve_alerts"),
    path("api/servers/<int:server_id>/alerts/<str:action>/", views.toggle_alert_suppression, name="toggle_alert_suppression"),
    path("api/servers/<int:server_id>/monitoring/<str:action>/", views.toggle_monitoring, name="toggle_monitoring"),
    path("api/server/<int:server_id>/top-processes/", views.get_top_cpu_processes, name="top_cpu_processes"),
    path("api/server/<int:server_id>/top-ram-processes/", views.get_top_ram_processes, name="top_ram_processes"),
    path("api/server/<int:server_id>/active-services/", views.get_active_services, name="active_services"),
    path("api/server/<int:server_id>/services/", views.get_server_services, name="get_server_services"),
    path("api/server/<int:server_id>/services/monitor/", views.update_monitored_services, name="update_monitored_services"),
    path("api/server/<int:server_id>/services/thresholds/", views.update_service_thresholds, name="update_service_thresholds"),
    path("api/server/<int:server_id>/service/<int:service_id>/toggle-monitoring/", views.toggle_service_monitoring, name="toggle_service_monitoring"),
    path("api/server/<int:server_id>/anomaly-status/", views.anomaly_status_api, name="anomaly_status_api"),
    path("api/server/<int:server_id>/metric-history/", views.metric_history_api, name="metric_history_api"),
    path("api/server/<int:server_id>/metrics/", views.server_metrics_api, name="server_metrics_api"),
    path("api/server/<int:server_id>/disk-io/", views.disk_io_api, name="disk_io_api"),
    path("api/server/<int:server_id>/network-io/", views.network_io_api, name="network_io_api"),
    path("api/server/<int:server_id>/monitored-disks/", views.update_monitored_disks, name="update_monitored_disks"),
    path("api/anomalies/<int:anomaly_id>/", views.anomaly_detail_api, name="anomaly_detail_api"),
    path("api/anomalies/<int:anomaly_id>/resolve/", views.anomaly_resolve_api, name="anomaly_resolve_api"),
    path("api/anomalies/bulk-resolve/", views.anomaly_bulk_resolve_api, name="anomaly_bulk_resolve_api"),
    path("api/dashboard/news-feed/", views.dashboard_news_feed_api, name="dashboard_news_feed_api"),
    path("log-troubleshooting/", views.log_troubleshooting_config, name="log_troubleshooting_config"),
    path("api/log-troubleshooting/add/", views.log_troubleshooting_add, name="log_troubleshooting_add"),
    path("api/log-troubleshooting/create-solution/", views.log_troubleshooting_create_solution, name="log_troubleshooting_create_solution"),
    path("log-troubleshooting/results/", views.log_troubleshooting_results, name="log_troubleshooting_results"),
    path("help/", views.help_docs, name="help_docs"),
    path("logout/", views.custom_logout, name="logout"),
    # RBAC URLs
    path("roles/", views.role_management, name="role_management"),
    path("roles/create/", views.create_role, name="create_role"),
    path("roles/edit/<int:role_id>/", views.edit_role, name="edit_role"),
    path("roles/delete/<int:role_id>/", views.delete_role, name="delete_role"),
    path("design-system-demo/", views.demo_dashboard, name="demo_dashboard"),
]

